name: TFC Action

on:
    push: 
    

jobs:
    tfc:
        runs-on: ubuntu-latest
        steps:
            - name: Create TFC Workspace
              uses: ibrt2016/actions-tfc-create-workspace@main
              with:
                token: ${{ secrets.TF_ORG_TOKEN }}
                name: ${{ github.event.repository.name }}-dev
                org: hcta-azure-demo1221
                env: dev
                